# -*- coding: utf-8 -*-
"""20230928.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PGQjhFGOHTfP7jmyS0NV1pN2mC89ZA9w

spyder執行
"""

import sqlite3
conn = sqlite3.connect("students.db")
cursor = conn.cursor()
cursor.execute("""CREATE TABLE IF NOT EXISTS students(id INTEGER PRIMARY KEY, name TEXT, age INTEGER, grade REAL)""")
cursor.execute("INSERT INTO students (name, age, grade) VALUES ('A', 20, 90.5)")
cursor.execute("INSERT INTO students (name, age, grade) VALUES ('B', 18, 85.0)")
conn.commit()
cursor.execute("SELECT * FROM students")
students = cursor.fetchall()
for i in students:
    print(i)
#更新
cursor.execute("UPDATE students SET grade = 95.0 WHERE name = 'A'")
conn.commit()
cursor.execute("SELECT * FROM students")
students = cursor.fetchall()
for i in students:
    print(i)
#刪除
cursor.execute("DELETE FROM students WHERE NAME = 'B'")
conn.commit()
cursor.execute("SELECT * FROM students")
students = cursor.fetchall()
for i in students:
    print(i)
cursor.close()
conn.close()

import sqlite3
conn = sqlite3.connect("meat.db")
cursor = conn.cursor()
cursor.execute("""CREATE TABLE IF NOT EXISTS meats(id INTEGER PRIMARY KEY, name TEXT, price INTEGER, quantity integer)""")
cursor.execute("INSERT INTO meats (name, price, quantity) VALUES ('chicken', 30, 5)")
cursor.execute("INSERT INTO meats (name, price, quantity) VALUES ('beaf', 55, 10)")
cursor.execute("INSERT INTO meats (name, price, quantity) VALUES ('pork', 40, 15)")
conn.commit()
cursor.execute("SELECT * FROM meats")
students = cursor.fetchall()
print("第一次:")
for i in students:
    print(i)
#更新
cursor.execute("UPDATE meats SET price = 35 WHERE name = 'pork'")
cursor.execute("UPDATE meats SET quantity = 30 WHERE name = 'chicken'")
conn.commit()
cursor.execute("SELECT * FROM meats")
print("第二次:")
students = cursor.fetchall()
for i in students:
    print(i)
#刪除
cursor.execute("DELETE FROM meats WHERE price = 40")
conn.commit()
cursor.execute("SELECT * FROM meats")
students = cursor.fetchall()
print("第三次:")
for i in students:
    print(i)
cursor.close()
conn.close()